version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "mongodb+srv://frankyliu1996_db_user:yXLc2y1ybFbKee7W@imy220projectcluster.w35t9gj.mongodb.net/?retryWrites=true&w=majority&appName=IMY220ProjectCluster"
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped